SET FOREIGN_KEY_CHECKS = 0;

DROP DATABASE IF EXISTS `spring_data`;
CREATE DATABASE IF NOT EXISTS `spring_data`;

SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE spring_data.`TALK` (
  TALK_ID               BIGINT(20) NOT NULL AUTO_INCREMENT,
  FK_SPEAKER_ID     	BIGINT(20),
  TITLE         	VARCHAR(255),
DATE 			DATETIME,
PRIMARY KEY (TALK_ID)
);

CREATE TABLE spring_data.SPEAKER (
  SPEAKER_ID                BIGINT(20)   NOT NULL AUTO_INCREMENT,
  NAME                      VARCHAR(255),
  PRIMARY KEY (SPEAKER_ID)
);

ALTER TABLE spring_data.`TALK`
ADD INDEX FKUSER371650 (FK_SPEAKER_ID),
ADD CONSTRAINT FKUSER371650 FOREIGN KEY (FK_SPEAKER_ID) REFERENCES spring_data.SPEAKER (SPEAKER_ID);
